"""add_date_to_tests

Revision ID: 2bc16ad04872
Revises: 320e77e8eeae
Create Date: 2025-08-29 06:46:16.958147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc16ad04872'
down_revision: Union[str, Sequence[str], None] = '320e77e8eeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'date')
    # ### end Alembic commands ###
