"""add_category_to_tests

Revision ID: 320e77e8eeae
Revises: 46812d6d5a80
Create Date: 2025-08-29 06:27:56.984525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320e77e8eeae'
down_revision: Union[str, Sequence[str], None] = '46812d6d5a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'category')
    # ### end Alembic commands ###
